/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "outline": "#859397",
              "primary-fixed-dim": "#00daf8",
              "on-primary-container": "#005f6d",
              "on-primary": "#00363f",
              "on-surface-variant": "#bac9cd",
              "surface": "#131313",
              "primary-fixed": "#a5eeff",
              "on-secondary": "#5e1700",
              "on-error-container": "#ffdad6",
              "tertiary-fixed": "#52ffac",
              "error": "#ffb4ab",
              "inverse-on-surface": "#313030",
              "on-surface": "#e5e2e1",
              "surface-dim": "#131313",
              "on-tertiary-container": "#00633d",
              "tertiary-container": "#00e995",
              "primary-container": "#00e0ff",
              "on-tertiary-fixed-variant": "#005231",
              "secondary-fixed": "#ffdbd0",
              "error-container": "#93000a",
              "inverse-primary": "#006877",
              "on-primary-fixed": "#001f25",
              "on-secondary-container": "#521300",
              "tertiary": "#8dffbe",
              "on-tertiary": "#003920",
              "surface-bright": "#393939",
              "secondary": "#ffb59e",
              "tertiary-fixed-dim": "#00e290",
              "on-secondary-fixed-variant": "#852400",
              "surface-tint": "#00daf8",
              "inverse-surface": "#e5e2e1",
              "secondary-container": "#ff571a",
              "on-primary-fixed-variant": "#004e5a",
              "on-secondary-fixed": "#3a0b00",
              "outline-variant": "#3b494c",
              "surface-container-lowest": "#0e0e0e",
              "surface-container-low": "#1c1b1b",
              "on-tertiary-fixed": "#002111",
              "background": "#131313",
              "primary": "#baf2ff",
              "surface-variant": "#353534",
              "on-error": "#690005",
              "secondary-fixed-dim": "#ffb59e",
              "surface-container": "#201f1f",
              "surface-container-high": "#2a2a2a",
              "on-background": "#e5e2e1",
              "surface-container-highest": "#353534"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "md": "24px",
              "lg": "40px",
              "gutter": "24px",
              "margin-mobile": "16px",
              "base": "8px",
              "margin-desktop": "48px",
              "sm": "12px",
              "xl": "64px",
              "xs": "4px"
      },
      "fontFamily": {
              "body-md": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "display-lg": ["Inter"],
              "headline-lg": ["Inter"],
              "body-lg": ["Inter"],
              "data-numeric": ["JetBrains Mono"],
              "label-caps": ["JetBrains Mono"],
              "headline-md": ["Inter"]
      },
      "fontSize": {
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "data-numeric": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
              "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
